# Generated by Django 5.0 on 2024-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_article_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
